// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: jobworkerp/service/runner.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { RunnerType } from "../data/common";
import { Runner, RunnerId, RunnerSortField } from "../data/runner";
import { CountCondition, CountResponse, FindListRequest, SuccessResponse } from "./common";

export const protobufPackage = "jobworkerp.service";

export interface CreateRunnerRequest {
  /**
   * # Runner Name
   * Unique key and proto message prefix (e.g. name: "command",
   * runner_settings_proto: "CommandRunnerSettings", job_args_proto:
   * "CommandArg")
   */
  name: string;
  /**
   * # Runner Description
   * Description of runner implementation
   */
  description: string;
  /**
   * # Runner Type
   * can create runner type only: MCP, Plugin
   */
  runnerType: RunnerType;
  /**
   * # definition
   * runner definition
   * mcp: mcp_server toml
   * plugin: plugin filepath
   */
  definition: string;
}

export interface CreateRunnerResponse {
  /** generated id */
  id: RunnerId | undefined;
}

export interface OptionalRunnerResponse {
  data?: Runner | undefined;
}

export interface RunnerNameRequest {
  name: string;
}

export interface FindRunnerListRequest {
  /** Runner type filter (multiple types allowed) */
  runnerTypes: RunnerType[];
  /** Name prefix match filter (LIKE 'keyword%') */
  nameFilter?:
    | string
    | undefined;
  /** Pagination */
  limit?:
    | number
    | undefined;
  /** Default: 0, Max: 10000 */
  offset?:
    | string
    | undefined;
  /** Sort options */
  sortBy?:
    | RunnerSortField
    | undefined;
  /** Default: false (DESC) */
  ascending?: boolean | undefined;
}

export interface CountRunnerRequest {
  runnerTypes: RunnerType[];
  nameFilter?: string | undefined;
}

function createBaseCreateRunnerRequest(): CreateRunnerRequest {
  return { name: "", description: "", runnerType: 0, definition: "" };
}

export const CreateRunnerRequest: MessageFns<CreateRunnerRequest> = {
  encode(message: CreateRunnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.runnerType !== 0) {
      writer.uint32(24).int32(message.runnerType);
    }
    if (message.definition !== "") {
      writer.uint32(34).string(message.definition);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRunnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRunnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.runnerType = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.definition = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateRunnerRequest>): CreateRunnerRequest {
    return CreateRunnerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateRunnerRequest>): CreateRunnerRequest {
    const message = createBaseCreateRunnerRequest();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.runnerType = object.runnerType ?? 0;
    message.definition = object.definition ?? "";
    return message;
  },
};

function createBaseCreateRunnerResponse(): CreateRunnerResponse {
  return { id: undefined };
}

export const CreateRunnerResponse: MessageFns<CreateRunnerResponse> = {
  encode(message: CreateRunnerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      RunnerId.encode(message.id, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRunnerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRunnerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = RunnerId.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateRunnerResponse>): CreateRunnerResponse {
    return CreateRunnerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateRunnerResponse>): CreateRunnerResponse {
    const message = createBaseCreateRunnerResponse();
    message.id = (object.id !== undefined && object.id !== null) ? RunnerId.fromPartial(object.id) : undefined;
    return message;
  },
};

function createBaseOptionalRunnerResponse(): OptionalRunnerResponse {
  return { data: undefined };
}

export const OptionalRunnerResponse: MessageFns<OptionalRunnerResponse> = {
  encode(message: OptionalRunnerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      Runner.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionalRunnerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionalRunnerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = Runner.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<OptionalRunnerResponse>): OptionalRunnerResponse {
    return OptionalRunnerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OptionalRunnerResponse>): OptionalRunnerResponse {
    const message = createBaseOptionalRunnerResponse();
    message.data = (object.data !== undefined && object.data !== null) ? Runner.fromPartial(object.data) : undefined;
    return message;
  },
};

function createBaseRunnerNameRequest(): RunnerNameRequest {
  return { name: "" };
}

export const RunnerNameRequest: MessageFns<RunnerNameRequest> = {
  encode(message: RunnerNameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnerNameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnerNameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RunnerNameRequest>): RunnerNameRequest {
    return RunnerNameRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnerNameRequest>): RunnerNameRequest {
    const message = createBaseRunnerNameRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseFindRunnerListRequest(): FindRunnerListRequest {
  return {
    runnerTypes: [],
    nameFilter: undefined,
    limit: undefined,
    offset: undefined,
    sortBy: undefined,
    ascending: undefined,
  };
}

export const FindRunnerListRequest: MessageFns<FindRunnerListRequest> = {
  encode(message: FindRunnerListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.runnerTypes) {
      writer.int32(v);
    }
    writer.join();
    if (message.nameFilter !== undefined) {
      writer.uint32(18).string(message.nameFilter);
    }
    if (message.limit !== undefined) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.offset !== undefined) {
      writer.uint32(32).int64(message.offset);
    }
    if (message.sortBy !== undefined) {
      writer.uint32(40).int32(message.sortBy);
    }
    if (message.ascending !== undefined) {
      writer.uint32(48).bool(message.ascending);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindRunnerListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindRunnerListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.runnerTypes.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.runnerTypes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nameFilter = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.offset = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.sortBy = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.ascending = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FindRunnerListRequest>): FindRunnerListRequest {
    return FindRunnerListRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindRunnerListRequest>): FindRunnerListRequest {
    const message = createBaseFindRunnerListRequest();
    message.runnerTypes = object.runnerTypes?.map((e) => e) || [];
    message.nameFilter = object.nameFilter ?? undefined;
    message.limit = object.limit ?? undefined;
    message.offset = object.offset ?? undefined;
    message.sortBy = object.sortBy ?? undefined;
    message.ascending = object.ascending ?? undefined;
    return message;
  },
};

function createBaseCountRunnerRequest(): CountRunnerRequest {
  return { runnerTypes: [], nameFilter: undefined };
}

export const CountRunnerRequest: MessageFns<CountRunnerRequest> = {
  encode(message: CountRunnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.runnerTypes) {
      writer.int32(v);
    }
    writer.join();
    if (message.nameFilter !== undefined) {
      writer.uint32(18).string(message.nameFilter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CountRunnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCountRunnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.runnerTypes.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.runnerTypes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nameFilter = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CountRunnerRequest>): CountRunnerRequest {
    return CountRunnerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CountRunnerRequest>): CountRunnerRequest {
    const message = createBaseCountRunnerRequest();
    message.runnerTypes = object.runnerTypes?.map((e) => e) || [];
    message.nameFilter = object.nameFilter ?? undefined;
    return message;
  },
};

export type RunnerServiceDefinition = typeof RunnerServiceDefinition;
export const RunnerServiceDefinition = {
  name: "RunnerService",
  fullName: "jobworkerp.service.RunnerService",
  methods: {
    create: {
      name: "Create",
      requestType: CreateRunnerRequest,
      requestStream: false,
      responseType: CreateRunnerResponse,
      responseStream: false,
      options: {},
    },
    delete: {
      name: "Delete",
      requestType: RunnerId,
      requestStream: false,
      responseType: SuccessResponse,
      responseStream: false,
      options: {},
    },
    find: {
      name: "Find",
      requestType: RunnerId,
      requestStream: false,
      responseType: OptionalRunnerResponse,
      responseStream: false,
      options: {},
    },
    findByName: {
      name: "FindByName",
      requestType: RunnerNameRequest,
      requestStream: false,
      responseType: OptionalRunnerResponse,
      responseStream: false,
      options: {},
    },
    /**
     * Deprecated: Use FindListBy instead. This method will be removed in version 2.0.0
     *
     * @deprecated
     */
    findList: {
      name: "FindList",
      requestType: FindListRequest,
      requestStream: false,
      responseType: Runner,
      responseStream: true,
      options: {},
    },
    /**
     * Deprecated: Use CountBy instead. This method will be removed in version 2.0.0
     *
     * @deprecated
     */
    count: {
      name: "Count",
      requestType: CountCondition,
      requestStream: false,
      responseType: CountResponse,
      responseStream: false,
      options: {},
    },
    /** New methods with filtering and sorting capabilities */
    findListBy: {
      name: "FindListBy",
      requestType: FindRunnerListRequest,
      requestStream: false,
      responseType: Runner,
      responseStream: true,
      options: {},
    },
    countBy: {
      name: "CountBy",
      requestType: CountRunnerRequest,
      requestStream: false,
      responseType: CountResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
