// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: jobworkerp/service/worker.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty, RunnerType } from "../data/common";
import { RunnerId } from "../data/runner";
import { Worker, WorkerData, WorkerId, WorkerSortField } from "../data/worker";
import { CountCondition, CountResponse, SuccessResponse } from "./common";

export const protobufPackage = "jobworkerp.service";

export interface CreateWorkerResponse {
  /** generated id */
  id: WorkerId | undefined;
}

export interface OptionalWorkerResponse {
  data?: Worker | undefined;
}

export interface WorkerNameRequest {
  name: string;
}

export interface FindWorkerListRequest {
  runnerTypes: RunnerType[];
  channel?: string | undefined;
  limit?: number | undefined;
  offset?:
    | string
    | undefined;
  /** New fields for admin UI (backward compatible) */
  nameFilter?:
    | string
    | undefined;
  /** true: periodic workers (periodic_interval > 0), false: non-periodic (= 0), null: all */
  isPeriodic?:
    | boolean
    | undefined;
  /** Filter by runner IDs */
  runnerIds: RunnerId[];
  /** Sort field */
  sortBy?:
    | WorkerSortField
    | undefined;
  /** Sort order (true: ASC, false: DESC) */
  ascending?: boolean | undefined;
}

export interface CountWorkerRequest {
  runnerTypes: RunnerType[];
  channel?: string | undefined;
  nameFilter?: string | undefined;
  isPeriodic?: boolean | undefined;
  runnerIds: RunnerId[];
}

export interface ChannelInfo {
  name: string;
  concurrency: number;
  /** Number of workers in this channel */
  workerCount: string;
}

export interface FindChannelListResponse {
  channels: ChannelInfo[];
}

function createBaseCreateWorkerResponse(): CreateWorkerResponse {
  return { id: undefined };
}

export const CreateWorkerResponse: MessageFns<CreateWorkerResponse> = {
  encode(message: CreateWorkerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      WorkerId.encode(message.id, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWorkerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWorkerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = WorkerId.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateWorkerResponse>): CreateWorkerResponse {
    return CreateWorkerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateWorkerResponse>): CreateWorkerResponse {
    const message = createBaseCreateWorkerResponse();
    message.id = (object.id !== undefined && object.id !== null) ? WorkerId.fromPartial(object.id) : undefined;
    return message;
  },
};

function createBaseOptionalWorkerResponse(): OptionalWorkerResponse {
  return { data: undefined };
}

export const OptionalWorkerResponse: MessageFns<OptionalWorkerResponse> = {
  encode(message: OptionalWorkerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      Worker.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionalWorkerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionalWorkerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = Worker.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<OptionalWorkerResponse>): OptionalWorkerResponse {
    return OptionalWorkerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OptionalWorkerResponse>): OptionalWorkerResponse {
    const message = createBaseOptionalWorkerResponse();
    message.data = (object.data !== undefined && object.data !== null) ? Worker.fromPartial(object.data) : undefined;
    return message;
  },
};

function createBaseWorkerNameRequest(): WorkerNameRequest {
  return { name: "" };
}

export const WorkerNameRequest: MessageFns<WorkerNameRequest> = {
  encode(message: WorkerNameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkerNameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkerNameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WorkerNameRequest>): WorkerNameRequest {
    return WorkerNameRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WorkerNameRequest>): WorkerNameRequest {
    const message = createBaseWorkerNameRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseFindWorkerListRequest(): FindWorkerListRequest {
  return {
    runnerTypes: [],
    channel: undefined,
    limit: undefined,
    offset: undefined,
    nameFilter: undefined,
    isPeriodic: undefined,
    runnerIds: [],
    sortBy: undefined,
    ascending: undefined,
  };
}

export const FindWorkerListRequest: MessageFns<FindWorkerListRequest> = {
  encode(message: FindWorkerListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.runnerTypes) {
      writer.int32(v);
    }
    writer.join();
    if (message.channel !== undefined) {
      writer.uint32(18).string(message.channel);
    }
    if (message.limit !== undefined) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.offset !== undefined) {
      writer.uint32(32).int64(message.offset);
    }
    if (message.nameFilter !== undefined) {
      writer.uint32(42).string(message.nameFilter);
    }
    if (message.isPeriodic !== undefined) {
      writer.uint32(48).bool(message.isPeriodic);
    }
    for (const v of message.runnerIds) {
      RunnerId.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.sortBy !== undefined) {
      writer.uint32(64).int32(message.sortBy);
    }
    if (message.ascending !== undefined) {
      writer.uint32(72).bool(message.ascending);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindWorkerListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindWorkerListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.runnerTypes.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.runnerTypes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.offset = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nameFilter = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isPeriodic = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.runnerIds.push(RunnerId.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.sortBy = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.ascending = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FindWorkerListRequest>): FindWorkerListRequest {
    return FindWorkerListRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindWorkerListRequest>): FindWorkerListRequest {
    const message = createBaseFindWorkerListRequest();
    message.runnerTypes = object.runnerTypes?.map((e) => e) || [];
    message.channel = object.channel ?? undefined;
    message.limit = object.limit ?? undefined;
    message.offset = object.offset ?? undefined;
    message.nameFilter = object.nameFilter ?? undefined;
    message.isPeriodic = object.isPeriodic ?? undefined;
    message.runnerIds = object.runnerIds?.map((e) => RunnerId.fromPartial(e)) || [];
    message.sortBy = object.sortBy ?? undefined;
    message.ascending = object.ascending ?? undefined;
    return message;
  },
};

function createBaseCountWorkerRequest(): CountWorkerRequest {
  return { runnerTypes: [], channel: undefined, nameFilter: undefined, isPeriodic: undefined, runnerIds: [] };
}

export const CountWorkerRequest: MessageFns<CountWorkerRequest> = {
  encode(message: CountWorkerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.runnerTypes) {
      writer.int32(v);
    }
    writer.join();
    if (message.channel !== undefined) {
      writer.uint32(18).string(message.channel);
    }
    if (message.nameFilter !== undefined) {
      writer.uint32(26).string(message.nameFilter);
    }
    if (message.isPeriodic !== undefined) {
      writer.uint32(32).bool(message.isPeriodic);
    }
    for (const v of message.runnerIds) {
      RunnerId.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CountWorkerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCountWorkerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.runnerTypes.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.runnerTypes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nameFilter = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isPeriodic = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.runnerIds.push(RunnerId.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CountWorkerRequest>): CountWorkerRequest {
    return CountWorkerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CountWorkerRequest>): CountWorkerRequest {
    const message = createBaseCountWorkerRequest();
    message.runnerTypes = object.runnerTypes?.map((e) => e) || [];
    message.channel = object.channel ?? undefined;
    message.nameFilter = object.nameFilter ?? undefined;
    message.isPeriodic = object.isPeriodic ?? undefined;
    message.runnerIds = object.runnerIds?.map((e) => RunnerId.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChannelInfo(): ChannelInfo {
  return { name: "", concurrency: 0, workerCount: "0" };
}

export const ChannelInfo: MessageFns<ChannelInfo> = {
  encode(message: ChannelInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.concurrency !== 0) {
      writer.uint32(16).uint32(message.concurrency);
    }
    if (message.workerCount !== "0") {
      writer.uint32(24).int64(message.workerCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.concurrency = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.workerCount = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ChannelInfo>): ChannelInfo {
    return ChannelInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChannelInfo>): ChannelInfo {
    const message = createBaseChannelInfo();
    message.name = object.name ?? "";
    message.concurrency = object.concurrency ?? 0;
    message.workerCount = object.workerCount ?? "0";
    return message;
  },
};

function createBaseFindChannelListResponse(): FindChannelListResponse {
  return { channels: [] };
}

export const FindChannelListResponse: MessageFns<FindChannelListResponse> = {
  encode(message: FindChannelListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.channels) {
      ChannelInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindChannelListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindChannelListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channels.push(ChannelInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FindChannelListResponse>): FindChannelListResponse {
    return FindChannelListResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindChannelListResponse>): FindChannelListResponse {
    const message = createBaseFindChannelListResponse();
    message.channels = object.channels?.map((e) => ChannelInfo.fromPartial(e)) || [];
    return message;
  },
};

export type WorkerServiceDefinition = typeof WorkerServiceDefinition;
export const WorkerServiceDefinition = {
  name: "WorkerService",
  fullName: "jobworkerp.service.WorkerService",
  methods: {
    create: {
      name: "Create",
      requestType: WorkerData,
      requestStream: false,
      responseType: CreateWorkerResponse,
      responseStream: false,
      options: {},
    },
    update: {
      name: "Update",
      requestType: Worker,
      requestStream: false,
      responseType: SuccessResponse,
      responseStream: false,
      options: {},
    },
    delete: {
      name: "Delete",
      requestType: WorkerId,
      requestStream: false,
      responseType: SuccessResponse,
      responseStream: false,
      options: {},
    },
    find: {
      name: "Find",
      requestType: WorkerId,
      requestStream: false,
      responseType: OptionalWorkerResponse,
      responseStream: false,
      options: {},
    },
    findByName: {
      name: "FindByName",
      requestType: WorkerNameRequest,
      requestStream: false,
      responseType: OptionalWorkerResponse,
      responseStream: false,
      options: {},
    },
    findList: {
      name: "FindList",
      requestType: FindWorkerListRequest,
      requestStream: false,
      responseType: Worker,
      responseStream: true,
      options: {},
    },
    /**
     * Deprecated: Use CountBy instead. This method will be removed in version 2.0.0
     *
     * @deprecated
     */
    count: {
      name: "Count",
      requestType: CountCondition,
      requestStream: false,
      responseType: CountResponse,
      responseStream: false,
      options: {},
    },
    countBy: {
      name: "CountBy",
      requestType: CountWorkerRequest,
      requestStream: false,
      responseType: CountResponse,
      responseStream: false,
      options: {},
    },
    findChannelList: {
      name: "FindChannelList",
      requestType: Empty,
      requestStream: false,
      responseType: FindChannelListResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
