// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v7.34.0
// source: jobworkerp/service/worker_instance.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../data/common";
import { WorkerInstance, WorkerInstanceId } from "../data/worker_instance";

export const protobufPackage = "jobworkerp.service";

/**
 * # Find Instance List Request
 * Request to retrieve worker instances
 */
export interface FindInstanceListRequest {
  /**
   * # Channel Filter
   * Filter by specific channel (optional)
   */
  channel?:
    | string
    | undefined;
  /**
   * # Active Only
   * If true, only return active instances (default: true)
   */
  activeOnly?: boolean | undefined;
}

/**
 * # Count Instance Response
 * Response containing worker instance counts
 */
export interface CountInstanceResponse {
  /**
   * # Total Count
   * Total number of registered instances
   */
  total: string;
  /**
   * # Active Count
   * Number of active instances (heartbeat within timeout)
   */
  active: string;
}

/**
 * # Instance Channel Info
 * Channel information aggregated from worker instances
 */
export interface InstanceChannelInfo {
  /**
   * # Channel Name
   * Channel name (default channel is displayed as "[default]")
   */
  name: string;
  /**
   * # Total Concurrency
   * Sum of concurrency from all active instances
   */
  totalConcurrency: number;
  /**
   * # Active Instances
   * Number of active instances processing this channel
   */
  activeInstances: number;
  /**
   * # Worker Count
   * Number of Worker definitions registered for this channel
   */
  workerCount: string;
}

/**
 * # Find Instance Channel List Response
 * Response containing aggregated channel information from instances
 */
export interface FindInstanceChannelListResponse {
  channels: InstanceChannelInfo[];
}

function createBaseFindInstanceListRequest(): FindInstanceListRequest {
  return { channel: undefined, activeOnly: undefined };
}

export const FindInstanceListRequest: MessageFns<FindInstanceListRequest> = {
  encode(message: FindInstanceListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channel !== undefined) {
      writer.uint32(10).string(message.channel);
    }
    if (message.activeOnly !== undefined) {
      writer.uint32(16).bool(message.activeOnly);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindInstanceListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindInstanceListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.activeOnly = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FindInstanceListRequest>): FindInstanceListRequest {
    return FindInstanceListRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindInstanceListRequest>): FindInstanceListRequest {
    const message = createBaseFindInstanceListRequest();
    message.channel = object.channel ?? undefined;
    message.activeOnly = object.activeOnly ?? undefined;
    return message;
  },
};

function createBaseCountInstanceResponse(): CountInstanceResponse {
  return { total: "0", active: "0" };
}

export const CountInstanceResponse: MessageFns<CountInstanceResponse> = {
  encode(message: CountInstanceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.total !== "0") {
      writer.uint32(8).int64(message.total);
    }
    if (message.active !== "0") {
      writer.uint32(16).int64(message.active);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CountInstanceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCountInstanceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.total = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.active = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CountInstanceResponse>): CountInstanceResponse {
    return CountInstanceResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CountInstanceResponse>): CountInstanceResponse {
    const message = createBaseCountInstanceResponse();
    message.total = object.total ?? "0";
    message.active = object.active ?? "0";
    return message;
  },
};

function createBaseInstanceChannelInfo(): InstanceChannelInfo {
  return { name: "", totalConcurrency: 0, activeInstances: 0, workerCount: "0" };
}

export const InstanceChannelInfo: MessageFns<InstanceChannelInfo> = {
  encode(message: InstanceChannelInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.totalConcurrency !== 0) {
      writer.uint32(16).uint32(message.totalConcurrency);
    }
    if (message.activeInstances !== 0) {
      writer.uint32(24).int32(message.activeInstances);
    }
    if (message.workerCount !== "0") {
      writer.uint32(32).int64(message.workerCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstanceChannelInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstanceChannelInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalConcurrency = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.activeInstances = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.workerCount = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<InstanceChannelInfo>): InstanceChannelInfo {
    return InstanceChannelInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<InstanceChannelInfo>): InstanceChannelInfo {
    const message = createBaseInstanceChannelInfo();
    message.name = object.name ?? "";
    message.totalConcurrency = object.totalConcurrency ?? 0;
    message.activeInstances = object.activeInstances ?? 0;
    message.workerCount = object.workerCount ?? "0";
    return message;
  },
};

function createBaseFindInstanceChannelListResponse(): FindInstanceChannelListResponse {
  return { channels: [] };
}

export const FindInstanceChannelListResponse: MessageFns<FindInstanceChannelListResponse> = {
  encode(message: FindInstanceChannelListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.channels) {
      InstanceChannelInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindInstanceChannelListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindInstanceChannelListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channels.push(InstanceChannelInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FindInstanceChannelListResponse>): FindInstanceChannelListResponse {
    return FindInstanceChannelListResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindInstanceChannelListResponse>): FindInstanceChannelListResponse {
    const message = createBaseFindInstanceChannelListResponse();
    message.channels = object.channels?.map((e) => InstanceChannelInfo.fromPartial(e)) || [];
    return message;
  },
};

/**
 * # Worker Instance Service
 * Service for managing and querying worker instances
 */
export type WorkerInstanceServiceDefinition = typeof WorkerInstanceServiceDefinition;
export const WorkerInstanceServiceDefinition = {
  name: "WorkerInstanceService",
  fullName: "jobworkerp.service.WorkerInstanceService",
  methods: {
    /**
     * # Find List
     * Retrieve worker instances as a stream
     */
    findList: {
      name: "FindList",
      requestType: FindInstanceListRequest,
      requestStream: false,
      responseType: WorkerInstance,
      responseStream: true,
      options: {},
    },
    /**
     * # Count
     * Get total and active instance counts
     */
    count: {
      name: "Count",
      requestType: Empty,
      requestStream: false,
      responseType: CountInstanceResponse,
      responseStream: false,
      options: {},
    },
    /**
     * # Find
     * Retrieve a specific worker instance by ID
     */
    find: {
      name: "Find",
      requestType: WorkerInstanceId,
      requestStream: false,
      responseType: WorkerInstance,
      responseStream: false,
      options: {},
    },
    /**
     * # Find Channel List
     * Get channel information aggregated from all active instances
     * This is the recommended API for getting accurate channel information
     */
    findChannelList: {
      name: "FindChannelList",
      requestType: Empty,
      requestStream: false,
      responseType: FindInstanceChannelListResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
