// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: jobworkerp/function/service/function.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { RunnerId } from "../../data/runner";
import { WorkerId } from "../../data/worker";
import { FunctionCallOptions, FunctionResult, FunctionSpecs, FunctionUsing, WorkerOptions } from "../data/function";

export const protobufPackage = "jobworkerp.function.service";

export interface FindFunctionRequest {
  excludeRunner: boolean;
  excludeWorker: boolean;
}

export interface FindFunctionSetRequest {
  /** FunctionSet name */
  name: string;
}

/** Function search request by name */
export interface FindFunctionByNameRequest {
  runnerName?: string | undefined;
  workerName?: string | undefined;
}

/** Function search response (for consistency with existing services) */
export interface OptionalFunctionSpecsResponse {
  /** Search result (None if not found) */
  data?: FunctionSpecs | undefined;
}

/** runner parameters to create as a worker */
export interface RunnerParameters {
  /** Runner Settings in JSON format (from protobuf schema) */
  settingsJson: string;
  /** Worker options (from protobuf schema) */
  workerOptions: WorkerOptions | undefined;
}

export interface FunctionCallRequest {
  runnerName?: string | undefined;
  workerName?:
    | string
    | undefined;
  /** Runner parameters (only for runner_name is set) */
  runnerParameters?:
    | RunnerParameters
    | undefined;
  /**
   * Job Arguments in JSON format (with protobuf schema:
   * jobworkerp.data.RunnerData.job_args_proto)
   */
  argsJson: string;
  /** Prevent from registering the same keys job in queue at the same time */
  uniqKey?:
    | string
    | undefined;
  /** Execution options */
  options?: FunctionCallOptions | undefined;
}

/**
 * # Create Worker Request
 * Create a Worker from any Runner with detailed configuration
 */
export interface CreateWorkerRequest {
  /** Runner name (e.g., "COMMAND", "HTTP_REQUEST") */
  runnerName?: string | undefined;
  runnerId?:
    | RunnerId
    | undefined;
  /** Worker name (unique identifier) */
  name: string;
  /** Worker description (optional) */
  description?:
    | string
    | undefined;
  /**
   * Runner settings in JSON format (from Runner's settings_schema)
   * Empty string or null if runner requires no settings
   */
  settingsJson?:
    | string
    | undefined;
  /** Worker options (execution configuration) */
  workerOptions?: WorkerOptions | undefined;
}

/** # Create Worker Response */
export interface CreateWorkerResponse {
  /** Created worker ID */
  workerId:
    | WorkerId
    | undefined;
  /** Created worker name */
  workerName: string;
}

/**
 * # Create Workflow Request
 * Create a REUSABLE_WORKFLOW Worker from workflow definition
 */
export interface CreateWorkflowRequest {
  /** Workflow definition as JSON or YAML string */
  workflowData?:
    | string
    | undefined;
  /** URL to workflow definition file (JSON or YAML) */
  workflowUrl?:
    | string
    | undefined;
  /**
   * Worker name (unique identifier)
   * If omitted, uses workflow's document.name field
   */
  name?:
    | string
    | undefined;
  /** Worker options (execution configuration) */
  workerOptions?: WorkerOptions | undefined;
}

/** # Create Workflow Response */
export interface CreateWorkflowResponse {
  /** Created worker ID */
  workerId:
    | WorkerId
    | undefined;
  /** Created worker name */
  workerName: string;
  /** Workflow document name (from definition) */
  workflowName?: string | undefined;
}

function createBaseFindFunctionRequest(): FindFunctionRequest {
  return { excludeRunner: false, excludeWorker: false };
}

export const FindFunctionRequest: MessageFns<FindFunctionRequest> = {
  encode(message: FindFunctionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.excludeRunner !== false) {
      writer.uint32(8).bool(message.excludeRunner);
    }
    if (message.excludeWorker !== false) {
      writer.uint32(16).bool(message.excludeWorker);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindFunctionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindFunctionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.excludeRunner = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.excludeWorker = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FindFunctionRequest>): FindFunctionRequest {
    return FindFunctionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindFunctionRequest>): FindFunctionRequest {
    const message = createBaseFindFunctionRequest();
    message.excludeRunner = object.excludeRunner ?? false;
    message.excludeWorker = object.excludeWorker ?? false;
    return message;
  },
};

function createBaseFindFunctionSetRequest(): FindFunctionSetRequest {
  return { name: "" };
}

export const FindFunctionSetRequest: MessageFns<FindFunctionSetRequest> = {
  encode(message: FindFunctionSetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindFunctionSetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindFunctionSetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FindFunctionSetRequest>): FindFunctionSetRequest {
    return FindFunctionSetRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindFunctionSetRequest>): FindFunctionSetRequest {
    const message = createBaseFindFunctionSetRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseFindFunctionByNameRequest(): FindFunctionByNameRequest {
  return { runnerName: undefined, workerName: undefined };
}

export const FindFunctionByNameRequest: MessageFns<FindFunctionByNameRequest> = {
  encode(message: FindFunctionByNameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runnerName !== undefined) {
      writer.uint32(10).string(message.runnerName);
    }
    if (message.workerName !== undefined) {
      writer.uint32(18).string(message.workerName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindFunctionByNameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindFunctionByNameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runnerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workerName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FindFunctionByNameRequest>): FindFunctionByNameRequest {
    return FindFunctionByNameRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindFunctionByNameRequest>): FindFunctionByNameRequest {
    const message = createBaseFindFunctionByNameRequest();
    message.runnerName = object.runnerName ?? undefined;
    message.workerName = object.workerName ?? undefined;
    return message;
  },
};

function createBaseOptionalFunctionSpecsResponse(): OptionalFunctionSpecsResponse {
  return { data: undefined };
}

export const OptionalFunctionSpecsResponse: MessageFns<OptionalFunctionSpecsResponse> = {
  encode(message: OptionalFunctionSpecsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      FunctionSpecs.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionalFunctionSpecsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionalFunctionSpecsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = FunctionSpecs.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<OptionalFunctionSpecsResponse>): OptionalFunctionSpecsResponse {
    return OptionalFunctionSpecsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OptionalFunctionSpecsResponse>): OptionalFunctionSpecsResponse {
    const message = createBaseOptionalFunctionSpecsResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? FunctionSpecs.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseRunnerParameters(): RunnerParameters {
  return { settingsJson: "", workerOptions: undefined };
}

export const RunnerParameters: MessageFns<RunnerParameters> = {
  encode(message: RunnerParameters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.settingsJson !== "") {
      writer.uint32(10).string(message.settingsJson);
    }
    if (message.workerOptions !== undefined) {
      WorkerOptions.encode(message.workerOptions, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunnerParameters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunnerParameters();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.settingsJson = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workerOptions = WorkerOptions.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RunnerParameters>): RunnerParameters {
    return RunnerParameters.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RunnerParameters>): RunnerParameters {
    const message = createBaseRunnerParameters();
    message.settingsJson = object.settingsJson ?? "";
    message.workerOptions = (object.workerOptions !== undefined && object.workerOptions !== null)
      ? WorkerOptions.fromPartial(object.workerOptions)
      : undefined;
    return message;
  },
};

function createBaseFunctionCallRequest(): FunctionCallRequest {
  return {
    runnerName: undefined,
    workerName: undefined,
    runnerParameters: undefined,
    argsJson: "",
    uniqKey: undefined,
    options: undefined,
  };
}

export const FunctionCallRequest: MessageFns<FunctionCallRequest> = {
  encode(message: FunctionCallRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runnerName !== undefined) {
      writer.uint32(10).string(message.runnerName);
    }
    if (message.workerName !== undefined) {
      writer.uint32(18).string(message.workerName);
    }
    if (message.runnerParameters !== undefined) {
      RunnerParameters.encode(message.runnerParameters, writer.uint32(26).fork()).join();
    }
    if (message.argsJson !== "") {
      writer.uint32(34).string(message.argsJson);
    }
    if (message.uniqKey !== undefined) {
      writer.uint32(42).string(message.uniqKey);
    }
    if (message.options !== undefined) {
      FunctionCallOptions.encode(message.options, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionCallRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionCallRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runnerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workerName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.runnerParameters = RunnerParameters.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.argsJson = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.uniqKey = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.options = FunctionCallOptions.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FunctionCallRequest>): FunctionCallRequest {
    return FunctionCallRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FunctionCallRequest>): FunctionCallRequest {
    const message = createBaseFunctionCallRequest();
    message.runnerName = object.runnerName ?? undefined;
    message.workerName = object.workerName ?? undefined;
    message.runnerParameters = (object.runnerParameters !== undefined && object.runnerParameters !== null)
      ? RunnerParameters.fromPartial(object.runnerParameters)
      : undefined;
    message.argsJson = object.argsJson ?? "";
    message.uniqKey = object.uniqKey ?? undefined;
    message.options = (object.options !== undefined && object.options !== null)
      ? FunctionCallOptions.fromPartial(object.options)
      : undefined;
    return message;
  },
};

function createBaseCreateWorkerRequest(): CreateWorkerRequest {
  return {
    runnerName: undefined,
    runnerId: undefined,
    name: "",
    description: undefined,
    settingsJson: undefined,
    workerOptions: undefined,
  };
}

export const CreateWorkerRequest: MessageFns<CreateWorkerRequest> = {
  encode(message: CreateWorkerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runnerName !== undefined) {
      writer.uint32(10).string(message.runnerName);
    }
    if (message.runnerId !== undefined) {
      RunnerId.encode(message.runnerId, writer.uint32(18).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(34).string(message.description);
    }
    if (message.settingsJson !== undefined) {
      writer.uint32(42).string(message.settingsJson);
    }
    if (message.workerOptions !== undefined) {
      WorkerOptions.encode(message.workerOptions, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWorkerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWorkerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runnerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.runnerId = RunnerId.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.settingsJson = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.workerOptions = WorkerOptions.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateWorkerRequest>): CreateWorkerRequest {
    return CreateWorkerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateWorkerRequest>): CreateWorkerRequest {
    const message = createBaseCreateWorkerRequest();
    message.runnerName = object.runnerName ?? undefined;
    message.runnerId = (object.runnerId !== undefined && object.runnerId !== null)
      ? RunnerId.fromPartial(object.runnerId)
      : undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.settingsJson = object.settingsJson ?? undefined;
    message.workerOptions = (object.workerOptions !== undefined && object.workerOptions !== null)
      ? WorkerOptions.fromPartial(object.workerOptions)
      : undefined;
    return message;
  },
};

function createBaseCreateWorkerResponse(): CreateWorkerResponse {
  return { workerId: undefined, workerName: "" };
}

export const CreateWorkerResponse: MessageFns<CreateWorkerResponse> = {
  encode(message: CreateWorkerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workerId !== undefined) {
      WorkerId.encode(message.workerId, writer.uint32(10).fork()).join();
    }
    if (message.workerName !== "") {
      writer.uint32(18).string(message.workerName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWorkerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWorkerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workerId = WorkerId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workerName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateWorkerResponse>): CreateWorkerResponse {
    return CreateWorkerResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateWorkerResponse>): CreateWorkerResponse {
    const message = createBaseCreateWorkerResponse();
    message.workerId = (object.workerId !== undefined && object.workerId !== null)
      ? WorkerId.fromPartial(object.workerId)
      : undefined;
    message.workerName = object.workerName ?? "";
    return message;
  },
};

function createBaseCreateWorkflowRequest(): CreateWorkflowRequest {
  return { workflowData: undefined, workflowUrl: undefined, name: undefined, workerOptions: undefined };
}

export const CreateWorkflowRequest: MessageFns<CreateWorkflowRequest> = {
  encode(message: CreateWorkflowRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workflowData !== undefined) {
      writer.uint32(10).string(message.workflowData);
    }
    if (message.workflowUrl !== undefined) {
      writer.uint32(18).string(message.workflowUrl);
    }
    if (message.name !== undefined) {
      writer.uint32(26).string(message.name);
    }
    if (message.workerOptions !== undefined) {
      WorkerOptions.encode(message.workerOptions, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWorkflowRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWorkflowRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workflowData = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workflowUrl = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.workerOptions = WorkerOptions.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateWorkflowRequest>): CreateWorkflowRequest {
    return CreateWorkflowRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateWorkflowRequest>): CreateWorkflowRequest {
    const message = createBaseCreateWorkflowRequest();
    message.workflowData = object.workflowData ?? undefined;
    message.workflowUrl = object.workflowUrl ?? undefined;
    message.name = object.name ?? undefined;
    message.workerOptions = (object.workerOptions !== undefined && object.workerOptions !== null)
      ? WorkerOptions.fromPartial(object.workerOptions)
      : undefined;
    return message;
  },
};

function createBaseCreateWorkflowResponse(): CreateWorkflowResponse {
  return { workerId: undefined, workerName: "", workflowName: undefined };
}

export const CreateWorkflowResponse: MessageFns<CreateWorkflowResponse> = {
  encode(message: CreateWorkflowResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workerId !== undefined) {
      WorkerId.encode(message.workerId, writer.uint32(10).fork()).join();
    }
    if (message.workerName !== "") {
      writer.uint32(18).string(message.workerName);
    }
    if (message.workflowName !== undefined) {
      writer.uint32(26).string(message.workflowName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWorkflowResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWorkflowResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workerId = WorkerId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workerName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.workflowName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateWorkflowResponse>): CreateWorkflowResponse {
    return CreateWorkflowResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateWorkflowResponse>): CreateWorkflowResponse {
    const message = createBaseCreateWorkflowResponse();
    message.workerId = (object.workerId !== undefined && object.workerId !== null)
      ? WorkerId.fromPartial(object.workerId)
      : undefined;
    message.workerName = object.workerName ?? "";
    message.workflowName = object.workflowName ?? undefined;
    return message;
  },
};

export type FunctionServiceDefinition = typeof FunctionServiceDefinition;
export const FunctionServiceDefinition = {
  name: "FunctionService",
  fullName: "jobworkerp.function.service.FunctionService",
  methods: {
    findList: {
      name: "FindList",
      requestType: FindFunctionRequest,
      requestStream: false,
      responseType: FunctionSpecs,
      responseStream: true,
      options: {},
    },
    findListBySet: {
      name: "FindListBySet",
      requestType: FindFunctionSetRequest,
      requestStream: false,
      responseType: FunctionSpecs,
      responseStream: true,
      options: {},
    },
    call: {
      name: "Call",
      requestType: FunctionCallRequest,
      requestStream: false,
      responseType: FunctionResult,
      responseStream: true,
      options: {},
    },
    /** Function search by function using (FunctionId + optional using) */
    find: {
      name: "Find",
      requestType: FunctionUsing,
      requestStream: false,
      responseType: OptionalFunctionSpecsResponse,
      responseStream: false,
      options: {},
    },
    /** Function search by function name */
    findByName: {
      name: "FindByName",
      requestType: FindFunctionByNameRequest,
      requestStream: false,
      responseType: OptionalFunctionSpecsResponse,
      responseStream: false,
      options: {},
    },
    /** Create a Worker from any Runner with detailed configuration */
    createWorker: {
      name: "CreateWorker",
      requestType: CreateWorkerRequest,
      requestStream: false,
      responseType: CreateWorkerResponse,
      responseStream: false,
      options: {},
    },
    /** Create a REUSABLE_WORKFLOW Worker from workflow definition */
    createWorkflow: {
      name: "CreateWorkflow",
      requestType: CreateWorkflowRequest,
      requestStream: false,
      responseType: CreateWorkflowResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
