// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: jobworkerp/function/service/function_set.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { CountCondition, CountResponse, FindListRequest, SuccessResponse } from "../../service/common";
import { FunctionSet, FunctionSetData, FunctionSetDetail, FunctionSetId } from "../data/function_set";

export const protobufPackage = "jobworkerp.function.service";

export interface CreateFunctionSetResponse {
  /** generated id */
  id: FunctionSetId | undefined;
}

export interface OptionalFunctionSetResponse {
  data?: FunctionSet | undefined;
}

export interface OptionalFunctionSetDetailResponse {
  data?: FunctionSetDetail | undefined;
}

export interface FindByNameRequest {
  name: string;
}

function createBaseCreateFunctionSetResponse(): CreateFunctionSetResponse {
  return { id: undefined };
}

export const CreateFunctionSetResponse: MessageFns<CreateFunctionSetResponse> = {
  encode(message: CreateFunctionSetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      FunctionSetId.encode(message.id, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateFunctionSetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateFunctionSetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = FunctionSetId.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateFunctionSetResponse>): CreateFunctionSetResponse {
    return CreateFunctionSetResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateFunctionSetResponse>): CreateFunctionSetResponse {
    const message = createBaseCreateFunctionSetResponse();
    message.id = (object.id !== undefined && object.id !== null) ? FunctionSetId.fromPartial(object.id) : undefined;
    return message;
  },
};

function createBaseOptionalFunctionSetResponse(): OptionalFunctionSetResponse {
  return { data: undefined };
}

export const OptionalFunctionSetResponse: MessageFns<OptionalFunctionSetResponse> = {
  encode(message: OptionalFunctionSetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      FunctionSet.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionalFunctionSetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionalFunctionSetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = FunctionSet.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<OptionalFunctionSetResponse>): OptionalFunctionSetResponse {
    return OptionalFunctionSetResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OptionalFunctionSetResponse>): OptionalFunctionSetResponse {
    const message = createBaseOptionalFunctionSetResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? FunctionSet.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseOptionalFunctionSetDetailResponse(): OptionalFunctionSetDetailResponse {
  return { data: undefined };
}

export const OptionalFunctionSetDetailResponse: MessageFns<OptionalFunctionSetDetailResponse> = {
  encode(message: OptionalFunctionSetDetailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      FunctionSetDetail.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionalFunctionSetDetailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionalFunctionSetDetailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = FunctionSetDetail.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<OptionalFunctionSetDetailResponse>): OptionalFunctionSetDetailResponse {
    return OptionalFunctionSetDetailResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OptionalFunctionSetDetailResponse>): OptionalFunctionSetDetailResponse {
    const message = createBaseOptionalFunctionSetDetailResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? FunctionSetDetail.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseFindByNameRequest(): FindByNameRequest {
  return { name: "" };
}

export const FindByNameRequest: MessageFns<FindByNameRequest> = {
  encode(message: FindByNameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindByNameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindByNameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FindByNameRequest>): FindByNameRequest {
    return FindByNameRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FindByNameRequest>): FindByNameRequest {
    const message = createBaseFindByNameRequest();
    message.name = object.name ?? "";
    return message;
  },
};

export type FunctionSetServiceDefinition = typeof FunctionSetServiceDefinition;
export const FunctionSetServiceDefinition = {
  name: "FunctionSetService",
  fullName: "jobworkerp.function.service.FunctionSetService",
  methods: {
    create: {
      name: "Create",
      requestType: FunctionSetData,
      requestStream: false,
      responseType: CreateFunctionSetResponse,
      responseStream: false,
      options: {},
    },
    update: {
      name: "Update",
      requestType: FunctionSet,
      requestStream: false,
      responseType: SuccessResponse,
      responseStream: false,
      options: {},
    },
    delete: {
      name: "Delete",
      requestType: FunctionSetId,
      requestStream: false,
      responseType: SuccessResponse,
      responseStream: false,
      options: {},
    },
    find: {
      name: "Find",
      requestType: FunctionSetId,
      requestStream: false,
      responseType: OptionalFunctionSetResponse,
      responseStream: false,
      options: {},
    },
    findByName: {
      name: "FindByName",
      requestType: FindByNameRequest,
      requestStream: false,
      responseType: OptionalFunctionSetResponse,
      responseStream: false,
      options: {},
    },
    findList: {
      name: "FindList",
      requestType: FindListRequest,
      requestStream: false,
      responseType: FunctionSet,
      responseStream: true,
      options: {},
    },
    count: {
      name: "Count",
      requestType: CountCondition,
      requestStream: false,
      responseType: CountResponse,
      responseStream: false,
      options: {},
    },
    /** New APIs for detailed function information */
    findDetail: {
      name: "FindDetail",
      requestType: FunctionSetId,
      requestStream: false,
      responseType: OptionalFunctionSetDetailResponse,
      responseStream: false,
      options: {},
    },
    findDetailByName: {
      name: "FindDetailByName",
      requestType: FindByNameRequest,
      requestStream: false,
      responseType: OptionalFunctionSetDetailResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
