// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: jobworkerp/data/job.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Priority, ResponseType, RetryPolicy, StreamingType } from "./common";
import { WorkerId } from "./worker";

export const protobufPackage = "jobworkerp.data";

/**
 * # Job Execution Overrides
 * Per-job overrides for execution settings normally defined at the worker level.
 * All fields are optional; when omitted, the worker's default is used.
 */
export interface JobExecutionOverrides {
  /** # Response Type Override */
  responseType?:
    | ResponseType
    | undefined;
  /** # Store Success Override */
  storeSuccess?:
    | boolean
    | undefined;
  /** # Store Failure Override */
  storeFailure?:
    | boolean
    | undefined;
  /** # Broadcast Results Override */
  broadcastResults?:
    | boolean
    | undefined;
  /** # Retry Policy Override */
  retryPolicy?: RetryPolicy | undefined;
}

/**
 * # Job Data
 * Configuration and state for a job that will be executed by a worker
 */
export interface JobData {
  /**
   * # Worker ID
   * Reference to the worker that will execute this job
   */
  workerId:
    | WorkerId
    | undefined;
  /**
   * # Job Arguments
   * Serialized arguments that will be passed to the runner
   */
  args: Uint8Array;
  /**
   * # Unique Key
   * Optional identifier to prevent duplicate job registration
   * Jobs with the same unique key cannot be registered simultaneously
   */
  uniqKey?:
    | string
    | undefined;
  /**
   * # Enqueue Time
   * Timestamp when the job was registered in the queue (Unix time in milliseconds)
   */
  enqueueTime: string;
  /**
   * # Grabbed Until Time
   * Timestamp until which the job is locked for processing (Unix time in
   * milliseconds) This should not be specified manually - it's set by the system
   */
  grabbedUntilTime?:
    | string
    | undefined;
  /**
   * # Run After Time
   * Timestamp when the job should be executed (Unix time in milliseconds)
   * Jobs will not be processed until this time is reached
   */
  runAfterTime: string;
  /**
   * # Retry Count
   * Number of times this job has been retried after failure
   */
  retried: number;
  /**
   * # Priority
   * Execution priority level: -1 (low), 0 (normal), 1 (high)
   * Note: Using enum directly in proto is not possible due to reference
   * limitations
   */
  priority: Priority;
  /**
   * # Timeout
   * Maximum execution time for the job in milliseconds
   * Job will be terminated if it exceeds this duration
   */
  timeout: string;
  /**
   * # Streaming Type
   * Defines how streaming is handled for this job execution.
   * - STREAMING_TYPE_NONE (default): Non-streaming execution using run()
   * - STREAMING_TYPE_INTERNAL: Uses run_stream() internally but collects
   *   result with collect_stream() and returns as single JobResult
   * - STREAMING_TYPE_RESPONSE: Full streaming, results streamed to client
   */
  streamingType: StreamingType;
  /**
   * # Using
   * Selects which method to use for multi-method runners
   * - Required: For multi-method runners
   * - Auto-selected: When omitted for single-method runners
   * - Ignored: For single-method runners
   */
  using?:
    | string
    | undefined;
  /**
   * # Execution Overrides
   * Per-job overrides for worker-level execution settings.
   * When present, these settings override the worker's defaults.
   */
  overrides?: JobExecutionOverrides | undefined;
}

/**
 * # Job ID
 * Unique identifier for a job
 */
export interface JobId {
  value: string;
}

/**
 * # Job
 * A job that is executed by a worker
 */
export interface Job {
  id: JobId | undefined;
  data: JobData | undefined;
  metadata: { [key: string]: string };
}

export interface Job_MetadataEntry {
  key: string;
  value: string;
}

/**
 * # Job Internal
 * Internal queue payload exchanged between the gRPC front and workers.
 * Never exposed through the public JobService API; it wraps a Job with
 * execution-mode flags that should not be settable by external clients.
 */
export interface JobInternal {
  /** The job to dispatch. */
  job:
    | Job
    | undefined;
  /**
   * # Load Only
   * Config-check / pre-load mode. When true, the worker runs the Runner's
   * load() (validating settings and, for use_static, warming up the pool)
   * and skips run(). Used by WorkerService.Load.
   */
  loadOnly: boolean;
}

/**
 * Internal transport message for feed data over Redis Pub/Sub.
 * Not part of the public gRPC API.
 */
export interface FeedDataTransport {
  data: Uint8Array;
  isFinal: boolean;
}

function createBaseJobExecutionOverrides(): JobExecutionOverrides {
  return {
    responseType: undefined,
    storeSuccess: undefined,
    storeFailure: undefined,
    broadcastResults: undefined,
    retryPolicy: undefined,
  };
}

export const JobExecutionOverrides: MessageFns<JobExecutionOverrides> = {
  encode(message: JobExecutionOverrides, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseType !== undefined) {
      writer.uint32(8).int32(message.responseType);
    }
    if (message.storeSuccess !== undefined) {
      writer.uint32(16).bool(message.storeSuccess);
    }
    if (message.storeFailure !== undefined) {
      writer.uint32(24).bool(message.storeFailure);
    }
    if (message.broadcastResults !== undefined) {
      writer.uint32(32).bool(message.broadcastResults);
    }
    if (message.retryPolicy !== undefined) {
      RetryPolicy.encode(message.retryPolicy, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobExecutionOverrides {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobExecutionOverrides();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.responseType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.storeSuccess = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.storeFailure = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.broadcastResults = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.retryPolicy = RetryPolicy.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<JobExecutionOverrides>): JobExecutionOverrides {
    return JobExecutionOverrides.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobExecutionOverrides>): JobExecutionOverrides {
    const message = createBaseJobExecutionOverrides();
    message.responseType = object.responseType ?? undefined;
    message.storeSuccess = object.storeSuccess ?? undefined;
    message.storeFailure = object.storeFailure ?? undefined;
    message.broadcastResults = object.broadcastResults ?? undefined;
    message.retryPolicy = (object.retryPolicy !== undefined && object.retryPolicy !== null)
      ? RetryPolicy.fromPartial(object.retryPolicy)
      : undefined;
    return message;
  },
};

function createBaseJobData(): JobData {
  return {
    workerId: undefined,
    args: new Uint8Array(0),
    uniqKey: undefined,
    enqueueTime: "0",
    grabbedUntilTime: undefined,
    runAfterTime: "0",
    retried: 0,
    priority: 0,
    timeout: "0",
    streamingType: 0,
    using: undefined,
    overrides: undefined,
  };
}

export const JobData: MessageFns<JobData> = {
  encode(message: JobData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workerId !== undefined) {
      WorkerId.encode(message.workerId, writer.uint32(10).fork()).join();
    }
    if (message.args.length !== 0) {
      writer.uint32(18).bytes(message.args);
    }
    if (message.uniqKey !== undefined) {
      writer.uint32(26).string(message.uniqKey);
    }
    if (message.enqueueTime !== "0") {
      writer.uint32(32).int64(message.enqueueTime);
    }
    if (message.grabbedUntilTime !== undefined) {
      writer.uint32(40).int64(message.grabbedUntilTime);
    }
    if (message.runAfterTime !== "0") {
      writer.uint32(48).int64(message.runAfterTime);
    }
    if (message.retried !== 0) {
      writer.uint32(56).uint32(message.retried);
    }
    if (message.priority !== 0) {
      writer.uint32(64).int32(message.priority);
    }
    if (message.timeout !== "0") {
      writer.uint32(72).uint64(message.timeout);
    }
    if (message.streamingType !== 0) {
      writer.uint32(96).int32(message.streamingType);
    }
    if (message.using !== undefined) {
      writer.uint32(90).string(message.using);
    }
    if (message.overrides !== undefined) {
      JobExecutionOverrides.encode(message.overrides, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workerId = WorkerId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.args = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.uniqKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.enqueueTime = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.grabbedUntilTime = reader.int64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.runAfterTime = reader.int64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.retried = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.priority = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.timeout = reader.uint64().toString();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.streamingType = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.using = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.overrides = JobExecutionOverrides.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<JobData>): JobData {
    return JobData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobData>): JobData {
    const message = createBaseJobData();
    message.workerId = (object.workerId !== undefined && object.workerId !== null)
      ? WorkerId.fromPartial(object.workerId)
      : undefined;
    message.args = object.args ?? new Uint8Array(0);
    message.uniqKey = object.uniqKey ?? undefined;
    message.enqueueTime = object.enqueueTime ?? "0";
    message.grabbedUntilTime = object.grabbedUntilTime ?? undefined;
    message.runAfterTime = object.runAfterTime ?? "0";
    message.retried = object.retried ?? 0;
    message.priority = object.priority ?? 0;
    message.timeout = object.timeout ?? "0";
    message.streamingType = object.streamingType ?? 0;
    message.using = object.using ?? undefined;
    message.overrides = (object.overrides !== undefined && object.overrides !== null)
      ? JobExecutionOverrides.fromPartial(object.overrides)
      : undefined;
    return message;
  },
};

function createBaseJobId(): JobId {
  return { value: "0" };
}

export const JobId: MessageFns<JobId> = {
  encode(message: JobId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "0") {
      writer.uint32(8).int64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<JobId>): JobId {
    return JobId.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobId>): JobId {
    const message = createBaseJobId();
    message.value = object.value ?? "0";
    return message;
  },
};

function createBaseJob(): Job {
  return { id: undefined, data: undefined, metadata: {} };
}

export const Job: MessageFns<Job> = {
  encode(message: Job, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      JobId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.data !== undefined) {
      JobData.encode(message.data, writer.uint32(18).fork()).join();
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      Job_MetadataEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Job {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJob();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = JobId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = JobData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = Job_MetadataEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.metadata[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Job>): Job {
    return Job.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Job>): Job {
    const message = createBaseJob();
    message.id = (object.id !== undefined && object.id !== null) ? JobId.fromPartial(object.id) : undefined;
    message.data = (object.data !== undefined && object.data !== null) ? JobData.fromPartial(object.data) : undefined;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseJob_MetadataEntry(): Job_MetadataEntry {
  return { key: "", value: "" };
}

export const Job_MetadataEntry: MessageFns<Job_MetadataEntry> = {
  encode(message: Job_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Job_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJob_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Job_MetadataEntry>): Job_MetadataEntry {
    return Job_MetadataEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Job_MetadataEntry>): Job_MetadataEntry {
    const message = createBaseJob_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseJobInternal(): JobInternal {
  return { job: undefined, loadOnly: false };
}

export const JobInternal: MessageFns<JobInternal> = {
  encode(message: JobInternal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.job !== undefined) {
      Job.encode(message.job, writer.uint32(10).fork()).join();
    }
    if (message.loadOnly !== false) {
      writer.uint32(16).bool(message.loadOnly);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobInternal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobInternal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.job = Job.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.loadOnly = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<JobInternal>): JobInternal {
    return JobInternal.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JobInternal>): JobInternal {
    const message = createBaseJobInternal();
    message.job = (object.job !== undefined && object.job !== null) ? Job.fromPartial(object.job) : undefined;
    message.loadOnly = object.loadOnly ?? false;
    return message;
  },
};

function createBaseFeedDataTransport(): FeedDataTransport {
  return { data: new Uint8Array(0), isFinal: false };
}

export const FeedDataTransport: MessageFns<FeedDataTransport> = {
  encode(message: FeedDataTransport, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data.length !== 0) {
      writer.uint32(10).bytes(message.data);
    }
    if (message.isFinal !== false) {
      writer.uint32(16).bool(message.isFinal);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FeedDataTransport {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeedDataTransport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isFinal = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FeedDataTransport>): FeedDataTransport {
    return FeedDataTransport.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FeedDataTransport>): FeedDataTransport {
    const message = createBaseFeedDataTransport();
    message.data = object.data ?? new Uint8Array(0);
    message.isFinal = object.isFinal ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
