// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v7.34.0
// source: jobworkerp/data/worker_instance.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "jobworkerp.data";

/**
 * # Channel Config
 * Worker instance channel configuration
 */
export interface ChannelConfig {
  /**
   * # Channel Name
   * Empty string represents the default channel
   */
  name: string;
  /**
   * # Concurrency
   * Number of jobs that can be processed concurrently
   */
  concurrency: number;
}

/**
 * # Worker Instance ID
 * Unique identifier for a worker instance
 * Generated from IP address (upper 32 bits) and process ID (lower 32 bits)
 */
export interface WorkerInstanceId {
  value: string;
}

/**
 * # Worker Instance Data
 * Data describing a running worker instance
 */
export interface WorkerInstanceData {
  /**
   * # IP Address
   * IPv4 address of the worker instance (e.g., "192.168.1.100")
   */
  ipAddress: string;
  /**
   * # Hostname
   * Hostname of the worker instance (if available)
   */
  hostname?:
    | string
    | undefined;
  /**
   * # Channels
   * List of channels this worker instance processes with their concurrency
   */
  channels: ChannelConfig[];
  /**
   * # Registered At
   * Registration timestamp (Unix timestamp in milliseconds)
   */
  registeredAt: string;
  /**
   * # Last Heartbeat
   * Last heartbeat timestamp (Unix timestamp in milliseconds)
   * Used for active status detection in Scalable configuration
   * Used for freeze detection in Standalone configuration
   */
  lastHeartbeat: string;
}

/**
 * # Worker Instance
 * A running worker process with its identification and data
 */
export interface WorkerInstance {
  id: WorkerInstanceId | undefined;
  data: WorkerInstanceData | undefined;
}

function createBaseChannelConfig(): ChannelConfig {
  return { name: "", concurrency: 0 };
}

export const ChannelConfig: MessageFns<ChannelConfig> = {
  encode(message: ChannelConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.concurrency !== 0) {
      writer.uint32(16).uint32(message.concurrency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.concurrency = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ChannelConfig>): ChannelConfig {
    return ChannelConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChannelConfig>): ChannelConfig {
    const message = createBaseChannelConfig();
    message.name = object.name ?? "";
    message.concurrency = object.concurrency ?? 0;
    return message;
  },
};

function createBaseWorkerInstanceId(): WorkerInstanceId {
  return { value: "0" };
}

export const WorkerInstanceId: MessageFns<WorkerInstanceId> = {
  encode(message: WorkerInstanceId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "0") {
      writer.uint32(8).int64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkerInstanceId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkerInstanceId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WorkerInstanceId>): WorkerInstanceId {
    return WorkerInstanceId.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WorkerInstanceId>): WorkerInstanceId {
    const message = createBaseWorkerInstanceId();
    message.value = object.value ?? "0";
    return message;
  },
};

function createBaseWorkerInstanceData(): WorkerInstanceData {
  return { ipAddress: "", hostname: undefined, channels: [], registeredAt: "0", lastHeartbeat: "0" };
}

export const WorkerInstanceData: MessageFns<WorkerInstanceData> = {
  encode(message: WorkerInstanceData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ipAddress !== "") {
      writer.uint32(10).string(message.ipAddress);
    }
    if (message.hostname !== undefined) {
      writer.uint32(18).string(message.hostname);
    }
    for (const v of message.channels) {
      ChannelConfig.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.registeredAt !== "0") {
      writer.uint32(32).int64(message.registeredAt);
    }
    if (message.lastHeartbeat !== "0") {
      writer.uint32(40).int64(message.lastHeartbeat);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkerInstanceData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkerInstanceData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ipAddress = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.hostname = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.channels.push(ChannelConfig.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.registeredAt = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lastHeartbeat = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WorkerInstanceData>): WorkerInstanceData {
    return WorkerInstanceData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WorkerInstanceData>): WorkerInstanceData {
    const message = createBaseWorkerInstanceData();
    message.ipAddress = object.ipAddress ?? "";
    message.hostname = object.hostname ?? undefined;
    message.channels = object.channels?.map((e) => ChannelConfig.fromPartial(e)) || [];
    message.registeredAt = object.registeredAt ?? "0";
    message.lastHeartbeat = object.lastHeartbeat ?? "0";
    return message;
  },
};

function createBaseWorkerInstance(): WorkerInstance {
  return { id: undefined, data: undefined };
}

export const WorkerInstance: MessageFns<WorkerInstance> = {
  encode(message: WorkerInstance, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      WorkerInstanceId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.data !== undefined) {
      WorkerInstanceData.encode(message.data, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkerInstance {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkerInstance();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = WorkerInstanceId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = WorkerInstanceData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WorkerInstance>): WorkerInstance {
    return WorkerInstance.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WorkerInstance>): WorkerInstance {
    const message = createBaseWorkerInstance();
    message.id = (object.id !== undefined && object.id !== null) ? WorkerInstanceId.fromPartial(object.id) : undefined;
    message.data = (object.data !== undefined && object.data !== null)
      ? WorkerInstanceData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
