// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: jobworkerp/data/worker.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { QueueType, ResponseType, RetryPolicy } from "./common";
import { RunnerId } from "./runner";

export const protobufPackage = "jobworkerp.data";

/**
 * # Worker Sort Field
 * Defines the fields available for sorting workers in queries
 */
export enum WorkerSortField {
  WORKER_SORT_FIELD_UNSPECIFIED = 0,
  WORKER_SORT_FIELD_ID = 1,
  WORKER_SORT_FIELD_NAME = 2,
  WORKER_SORT_FIELD_RUNNER_ID = 3,
  WORKER_SORT_FIELD_PERIODIC_INTERVAL = 4,
  WORKER_SORT_FIELD_CREATED_AT = 5,
  UNRECOGNIZED = -1,
}

/**
 * # Worker Data
 * Configuration for worker execution
 */
export interface WorkerData {
  /**
   * # Worker Name
   * Unique identifier for the worker
   */
  name: string;
  /**
   * # Description
   * Description of the worker
   */
  description: string;
  /**
   * # Runner ID
   * Reference to the runner implementation to use
   */
  runnerId:
    | RunnerId
    | undefined;
  /**
   * # Runner Settings
   * Configuration bytes for the specific runner (e.g. docker runner settings)
   */
  runnerSettings: Uint8Array;
  /**
   * # Retry Policy
   * Configuration for job retry behavior on failure
   */
  retryPolicy:
    | RetryPolicy
    | undefined;
  /**
   * # Periodic Interval
   * Milliseconds between periodic job executions (0: non-periodic)
   * If enabled, direct_response cannot be used
   */
  periodicInterval: number;
  /**
   * # Channel Name
   * Message channel for job (if empty, default channel will be used)
   */
  channel?:
    | string
    | undefined;
  /**
   * # Queue Type
   * 0: normal (no backup to database)
   * 1: with backup to database
   * 2: only to database (not in memory queue)
   */
  queueType: QueueType;
  /**
   * # Response Type
   * 0: no result
   * 1: direct response
   */
  responseType: ResponseType;
  /**
   * # Store Success Flag
   * If true, job results will be stored in database when execution succeeds
   */
  storeSuccess: boolean;
  /**
   * # Store Failure Flag
   * If true, job results will be stored in database when execution fails
   */
  storeFailure: boolean;
  /**
   * # Static Execution Flag
   * If true, fixed number instance of this worker will run at a time (with
   * lock)
   */
  useStatic: boolean;
  /**
   * # Output Broadcast Flag
   * Broadcast job results to all result listeners or not.
   * If false, cannot use JobResultService/{Listen, ListenStream,
   * ListenByWorker}.
   */
  broadcastResults: boolean;
}

export interface WorkerId {
  value: string;
}

/**
 * # Worker
 * A worker that loads a runner with specified settings and executes jobs by
 * providing arguments
 */
export interface Worker {
  id: WorkerId | undefined;
  data: WorkerData | undefined;
}

function createBaseWorkerData(): WorkerData {
  return {
    name: "",
    description: "",
    runnerId: undefined,
    runnerSettings: new Uint8Array(0),
    retryPolicy: undefined,
    periodicInterval: 0,
    channel: undefined,
    queueType: 0,
    responseType: 0,
    storeSuccess: false,
    storeFailure: false,
    useStatic: false,
    broadcastResults: false,
  };
}

export const WorkerData: MessageFns<WorkerData> = {
  encode(message: WorkerData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.runnerId !== undefined) {
      RunnerId.encode(message.runnerId, writer.uint32(26).fork()).join();
    }
    if (message.runnerSettings.length !== 0) {
      writer.uint32(34).bytes(message.runnerSettings);
    }
    if (message.retryPolicy !== undefined) {
      RetryPolicy.encode(message.retryPolicy, writer.uint32(42).fork()).join();
    }
    if (message.periodicInterval !== 0) {
      writer.uint32(48).uint32(message.periodicInterval);
    }
    if (message.channel !== undefined) {
      writer.uint32(58).string(message.channel);
    }
    if (message.queueType !== 0) {
      writer.uint32(64).int32(message.queueType);
    }
    if (message.responseType !== 0) {
      writer.uint32(72).int32(message.responseType);
    }
    if (message.storeSuccess !== false) {
      writer.uint32(80).bool(message.storeSuccess);
    }
    if (message.storeFailure !== false) {
      writer.uint32(88).bool(message.storeFailure);
    }
    if (message.useStatic !== false) {
      writer.uint32(104).bool(message.useStatic);
    }
    if (message.broadcastResults !== false) {
      writer.uint32(112).bool(message.broadcastResults);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkerData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkerData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.runnerId = RunnerId.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.runnerSettings = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.retryPolicy = RetryPolicy.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.periodicInterval = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.queueType = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.responseType = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.storeSuccess = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.storeFailure = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.useStatic = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.broadcastResults = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WorkerData>): WorkerData {
    return WorkerData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WorkerData>): WorkerData {
    const message = createBaseWorkerData();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.runnerId = (object.runnerId !== undefined && object.runnerId !== null)
      ? RunnerId.fromPartial(object.runnerId)
      : undefined;
    message.runnerSettings = object.runnerSettings ?? new Uint8Array(0);
    message.retryPolicy = (object.retryPolicy !== undefined && object.retryPolicy !== null)
      ? RetryPolicy.fromPartial(object.retryPolicy)
      : undefined;
    message.periodicInterval = object.periodicInterval ?? 0;
    message.channel = object.channel ?? undefined;
    message.queueType = object.queueType ?? 0;
    message.responseType = object.responseType ?? 0;
    message.storeSuccess = object.storeSuccess ?? false;
    message.storeFailure = object.storeFailure ?? false;
    message.useStatic = object.useStatic ?? false;
    message.broadcastResults = object.broadcastResults ?? false;
    return message;
  },
};

function createBaseWorkerId(): WorkerId {
  return { value: "0" };
}

export const WorkerId: MessageFns<WorkerId> = {
  encode(message: WorkerId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "0") {
      writer.uint32(8).int64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkerId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkerId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WorkerId>): WorkerId {
    return WorkerId.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WorkerId>): WorkerId {
    const message = createBaseWorkerId();
    message.value = object.value ?? "0";
    return message;
  },
};

function createBaseWorker(): Worker {
  return { id: undefined, data: undefined };
}

export const Worker: MessageFns<Worker> = {
  encode(message: Worker, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      WorkerId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.data !== undefined) {
      WorkerData.encode(message.data, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Worker {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorker();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = WorkerId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = WorkerData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Worker>): Worker {
    return Worker.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Worker>): Worker {
    const message = createBaseWorker();
    message.id = (object.id !== undefined && object.id !== null) ? WorkerId.fromPartial(object.id) : undefined;
    message.data = (object.data !== undefined && object.data !== null)
      ? WorkerData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
